"""Tests for the FITAGE v1.2 to v1.3 entity registry migration."""

from dataclasses import dataclass, replace
from types import SimpleNamespace

import pytest

from custom_components.fitage import async_migrate_entry
from custom_components.fitage.const import MEASUREMENT_METRICS
from custom_components.fitage.migration import (
    LegacyProfile,
    canonical_unique_id,
    legacy_profiles_from_entry_data,
    legacy_unique_id_mapping,
    migrate_entity_registry,
    parse_legacy_unique_id,
)


@dataclass(frozen=True)
class FakeRegistryEntry:
    """Registry fields relevant to the migration and preservation checks."""

    entity_id: str
    unique_id: str
    platform: str = "fitage"
    config_entry_id: str = "entry-1"
    domain: str = "sensor"
    device_id: str | None = "profile-device"
    disabled_by: str | None = None
    hidden_by: str | None = None
    name: str | None = None
    icon: str | None = None
    unit_of_measurement: str | None = None


class FakeRegistry:
    """Small in-memory implementation of the entity registry API used here."""

    def __init__(self, entries: list[FakeRegistryEntry]) -> None:
        self.entries = entries
        self.update_calls: list[tuple[str, str]] = []

    def async_get_entity_id(
        self, domain: str, platform: str, unique_id: str
    ) -> str | None:
        return next(
            (
                entry.entity_id
                for entry in self.entries
                if entry.domain == domain
                and entry.platform == platform
                and entry.unique_id == unique_id
            ),
            None,
        )

    def async_update_entity(
        self, entity_id: str, *, new_unique_id: str
    ) -> FakeRegistryEntry:
        if self.async_get_entity_id("sensor", "fitage", new_unique_id) is not None:
            raise ValueError("unique ID collision")
        index = next(
            index
            for index, entry in enumerate(self.entries)
            if entry.entity_id == entity_id
        )
        self.entries[index] = replace(self.entries[index], unique_id=new_unique_id)
        self.update_calls.append((entity_id, new_unique_id))
        return self.entries[index]


def _entry_data() -> dict[str, object]:
    return {
        "user_info": {"user_id": "primary-id", "account_name": "Primary"},
        "profiles_list": [
            {
                "user_id": "primary-id",
                "account_name": "Primary",
                "is_primary": True,
            },
            {
                "user_id": "sub-id",
                "account_name": "Melissa Example",
                "is_primary": False,
            },
        ],
    }


def _config_entry(data: dict[str, object] | None = None) -> SimpleNamespace:
    return SimpleNamespace(
        entry_id="entry-1",
        data=data or _entry_data(),
        version=1,
        minor_version=1,
    )


def test_legacy_mapping_covers_primary_and_subprofile_entities() -> None:
    """Exact v1.2 primary and subprofile forms map to canonical IDs."""
    profiles = legacy_profiles_from_entry_data(_entry_data())
    mapping = legacy_unique_id_mapping("entry-1", profiles)

    assert (
        mapping["entry-1_account_name_primary-id"] == "primary-id_profile_account_name"
    )
    assert mapping["entry-1_weight_primary-id"] == "primary-id_profile_weight"
    assert mapping["entry-1_height_primary-id"] == "primary-id_profile_height"
    assert mapping["entry-1_birthday_primary-id"] == "primary-id_profile_birthday"
    assert mapping["entry-1_email_primary-id"] == "primary-id_profile_email"
    assert mapping["entry-1_goal_weight_primary-id"] == "primary-id_goal_weight"
    assert mapping["entry-1_goal_bodyfat_primary-id"] == "primary-id_goal_bodyfat"
    assert mapping["entry-1_goal_water_primary-id"] == "primary-id_goal_water"
    assert (
        mapping["entry-1_measurement_weight_primary-id"]
        == "primary-id_measurement_weight"
    )
    assert (
        mapping["entry-1_melissa_example_measurement_bmi_sub-id"]
        == "sub-id_measurement_bmi"
    )
    assert mapping["entry-1_melissa_example_weight_sub-id"] == "sub-id_profile_weight"

    for metric in MEASUREMENT_METRICS:
        assert (
            mapping[f"entry-1_measurement_{metric}_primary-id"]
            == f"primary-id_measurement_{metric}"
        )


def test_parser_rejects_unknown_fuzzy_and_wrong_profile_ids() -> None:
    """Only entries generated by an exact known v1.2 pattern are accepted."""
    profiles = legacy_profiles_from_entry_data(_entry_data())

    assert parse_legacy_unique_id(
        "entry-1_melissa_example_goal_weight_sub-id", "entry-1", profiles
    ) == canonical_unique_id("sub-id", "goal", "weight")
    assert (
        parse_legacy_unique_id("entry-1_other_goal_weight_sub-id", "entry-1", profiles)
        is None
    )
    assert (
        parse_legacy_unique_id(
            "entry-1_melissa_example_goal_unknown_sub-id", "entry-1", profiles
        )
        is None
    )
    assert (
        parse_legacy_unique_id(
            "entry-1_melissa_example_goal_weight_wrong-id", "entry-1", profiles
        )
        is None
    )
    assert (
        parse_legacy_unique_id(
            "other-entry_melissa_example_goal_weight_sub-id", "entry-1", profiles
        )
        is None
    )


def test_profile_rename_does_not_affect_saved_v12_mapping() -> None:
    """The stored v1.2 name reconstructs the old ID after a cloud rename."""
    data = _entry_data()
    profiles = legacy_profiles_from_entry_data(data)

    assert (
        parse_legacy_unique_id(
            "entry-1_melissa_example_measurement_weight_sub-id",
            "entry-1",
            profiles,
        )
        == "sub-id_measurement_weight"
    )


def test_two_profiles_with_the_same_name_map_by_user_id() -> None:
    """Equal display names remain isolated by their profile IDs."""
    profiles = (
        LegacyProfile("first-id", "alex_"),
        LegacyProfile("second-id", "alex_"),
    )
    mapping = legacy_unique_id_mapping("entry-1", profiles)

    assert mapping["entry-1_alex_weight_first-id"] == "first-id_profile_weight"
    assert mapping["entry-1_alex_weight_second-id"] == "second-id_profile_weight"


def test_weight_entities_migrate_in_place_and_preserve_registry_properties() -> None:
    """Profile and measurement weight remain separate without changing entity IDs."""
    entries = [
        FakeRegistryEntry(
            entity_id="sensor.melissa_weight",
            unique_id="entry-1_melissa_example_weight_sub-id",
            disabled_by="user",
            hidden_by="user",
            name="My profile weight",
            icon="mdi:scale",
            unit_of_measurement="kg",
        ),
        FakeRegistryEntry(
            entity_id="sensor.melissa_weight_2",
            unique_id="entry-1_melissa_example_measurement_weight_sub-id",
            name="My latest weight",
        ),
    ]
    registry = FakeRegistry(entries)

    result = migrate_entity_registry(registry, _config_entry(), registry.entries.copy())

    assert result.migrated == 2
    assert result.collisions == 0
    profile_weight, measurement_weight = registry.entries
    assert profile_weight.entity_id == "sensor.melissa_weight"
    assert profile_weight.unique_id == "sub-id_profile_weight"
    assert profile_weight.disabled_by == "user"
    assert profile_weight.hidden_by == "user"
    assert profile_weight.name == "My profile weight"
    assert profile_weight.icon == "mdi:scale"
    assert profile_weight.unit_of_measurement == "kg"
    assert profile_weight.device_id == "profile-device"
    assert measurement_weight.entity_id == "sensor.melissa_weight_2"
    assert measurement_weight.unique_id == "sub-id_measurement_weight"
    assert measurement_weight.name == "My latest weight"
    assert measurement_weight.device_id == "profile-device"


def test_manual_entity_id_and_goal_entities_are_preserved() -> None:
    """Migration changes only unique IDs for manually named goal entities."""
    entries = [
        FakeRegistryEntry(
            entity_id="sensor.my_personal_target",
            unique_id="entry-1_goal_weight_primary-id",
            name="Personal target",
        ),
        FakeRegistryEntry(
            entity_id="sensor.bodyfat_target",
            unique_id="entry-1_goal_bodyfat_primary-id",
        ),
    ]
    registry = FakeRegistry(entries)

    result = migrate_entity_registry(registry, _config_entry(), registry.entries.copy())

    assert result.migrated == 2
    assert registry.entries[0].entity_id == "sensor.my_personal_target"
    assert registry.entries[0].unique_id == "primary-id_goal_weight"
    assert registry.entries[0].name == "Personal target"
    assert registry.entries[1].entity_id == "sensor.bodyfat_target"
    assert registry.entries[1].unique_id == "primary-id_goal_bodyfat"


def test_only_matching_fitage_sensor_entries_for_config_entry_are_migrated() -> None:
    """Wrong domain, platform, config entry, and unknown patterns are ignored."""
    entries = [
        FakeRegistryEntry(
            "binary_sensor.wrong", "entry-1_weight_primary-id", domain="binary_sensor"
        ),
        FakeRegistryEntry(
            "sensor.feelfit", "entry-1_weight_primary-id", platform="feelfit"
        ),
        FakeRegistryEntry(
            "sensor.other_entry", "entry-1_weight_primary-id", config_entry_id="entry-2"
        ),
        FakeRegistryEntry("sensor.unknown", "entry-1_unknown_primary-id"),
        FakeRegistryEntry("sensor.valid", "entry-1_weight_primary-id"),
    ]
    registry = FakeRegistry(entries)

    result = migrate_entity_registry(registry, _config_entry(), registry.entries.copy())

    assert result.migrated == 1
    assert registry.update_calls == [("sensor.valid", "primary-id_profile_weight")]
    assert registry.entries[1].platform == "feelfit"
    assert registry.entries[1].unique_id == "entry-1_weight_primary-id"


def test_canonical_collision_is_safe_noop() -> None:
    """An existing canonical identity is never overwritten or removed."""
    entries = [
        FakeRegistryEntry("sensor.old", "entry-1_weight_primary-id"),
        FakeRegistryEntry("sensor.new", "primary-id_profile_weight"),
    ]
    registry = FakeRegistry(entries)

    result = migrate_entity_registry(registry, _config_entry(), registry.entries.copy())

    assert result.migrated == 0
    assert result.collisions == 1
    assert registry.update_calls == []
    assert registry.entries == entries


def test_same_registry_entry_reported_for_canonical_id_is_noop() -> None:
    """A registry self-match is treated as already migrated without mutation."""

    class SelfMatchingRegistry(FakeRegistry):
        def async_get_entity_id(
            self, domain: str, platform: str, unique_id: str
        ) -> str | None:
            if unique_id == "primary-id_profile_weight":
                return "sensor.weight"
            return super().async_get_entity_id(domain, platform, unique_id)

    registry = SelfMatchingRegistry(
        [FakeRegistryEntry("sensor.weight", "entry-1_weight_primary-id")]
    )

    result = migrate_entity_registry(registry, _config_entry(), registry.entries.copy())

    assert result.migrated == 0
    assert result.collisions == 0
    assert registry.update_calls == []


def test_migration_is_idempotent() -> None:
    """A second run performs no updates and raises no errors."""
    registry = FakeRegistry(
        [FakeRegistryEntry("sensor.weight", "entry-1_weight_primary-id")]
    )
    entry = _config_entry()

    first = migrate_entity_registry(registry, entry, registry.entries.copy())
    second = migrate_entity_registry(registry, entry, registry.entries.copy())

    assert first.migrated == 1
    assert second.migrated == 0
    assert second.collisions == 0
    assert registry.update_calls == [("sensor.weight", "primary-id_profile_weight")]


def test_clean_v13_registry_needs_no_migration() -> None:
    """A clean registry with canonical entities is an unchanged no-op."""
    registry = FakeRegistry(
        [FakeRegistryEntry("sensor.weight", "primary-id_profile_weight")]
    )

    result = migrate_entity_registry(registry, _config_entry(), registry.entries.copy())

    assert result.migrated == 0
    assert result.collisions == 0
    assert registry.update_calls == []


@pytest.mark.asyncio
async def test_current_minor_version_is_clean_noop() -> None:
    """A clean v1.3 config entry does not access or mutate the registry."""
    entry = _config_entry()
    entry.minor_version = 2

    assert await async_migrate_entry(SimpleNamespace(), entry)
    assert entry.minor_version == 2


@pytest.mark.asyncio
async def test_config_entry_migration_runs_before_setup_and_bumps_minor_version(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Successful registry migration advances config entry version 1.1 to 1.2."""
    registry = FakeRegistry(
        [FakeRegistryEntry("sensor.weight", "entry-1_weight_primary-id")]
    )
    entry = _config_entry()

    class ConfigEntries:
        @staticmethod
        def async_update_entry(
            entry_to_update: SimpleNamespace, **changes: object
        ) -> None:
            for key, value in changes.items():
                setattr(entry_to_update, key, value)

    hass = SimpleNamespace(config_entries=ConfigEntries())
    monkeypatch.setattr(
        "custom_components.fitage.er.async_get", lambda unused_hass: registry
    )
    monkeypatch.setattr(
        "custom_components.fitage.er.async_entries_for_config_entry",
        lambda unused_registry, unused_entry_id: registry.entries.copy(),
    )

    assert await async_migrate_entry(hass, entry)
    assert entry.version == 1
    assert entry.minor_version == 2
    assert registry.entries[0].unique_id == "primary-id_profile_weight"


@pytest.mark.asyncio
async def test_config_entry_collision_does_not_advance_version(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A collision blocks setup and leaves the migration retryable."""
    registry = FakeRegistry(
        [
            FakeRegistryEntry("sensor.old", "entry-1_weight_primary-id"),
            FakeRegistryEntry("sensor.new", "primary-id_profile_weight"),
        ]
    )
    entry = _config_entry()
    hass = SimpleNamespace(config_entries=SimpleNamespace())
    monkeypatch.setattr(
        "custom_components.fitage.er.async_get", lambda unused_hass: registry
    )
    monkeypatch.setattr(
        "custom_components.fitage.er.async_entries_for_config_entry",
        lambda unused_registry, unused_entry_id: registry.entries.copy(),
    )

    assert not await async_migrate_entry(hass, entry)
    assert entry.minor_version == 1
    assert registry.update_calls == []
